adds failure handling when there is no connection
need-for-type/need-for-type pull request #19
Opened 2016-10-28 06:05 UTC by tiagonbotelho

2016-10-28 06:05 UTC, tiagonbotelho commented
@jbernardo95 review ;)

2016-10-28 13:08 UTC, jbernardo95 requested changes
@tiagonbotelho Looks fine !

Just a little thing, update the `CHANGELOG.md` ;)

2016-10-29 12:21 UTC, tiagonbotelho commented
@jbernardo95 please merge

2016-10-29 14:41 UTC, jbernardo95 approved these changes

2016-10-29 14:42 UTC, merged