Ascii art
need-for-type/need-for-type pull request #9
Opened 2016-09-15 23:10 UTC by jbernardo95

In response to #7.

2016-09-15 23:11 UTC, jbernardo95 commented
@tiagonbotelho Review please.

2016-09-16 15:11 UTC, tiagonbotelho commented on lib/need_for_type/display_window.rb
> +                                              |___/|_|"
http://patorjk.com/software/taag/#p=display&f=Slant&t=Need%20for%20Type perhaps this one is better 😄

2016-09-20 22:09 UTC, jbernardo95 commented
@tiagonbotelho Updated ;)

2016-09-23 17:18 UTC, tiagonbotelho commented on CHANGELOG.md
We should change this to log each version not added improved and fixed. This should be bumped for each version we have can you change that @jbernardo95 ?

2016-09-23 17:20 UTC, tiagonbotelho requested changes
Just left a final comment and it is good to go! Good job @jbernardo95 👍

2016-09-23 21:00 UTC, jbernardo95 commented on CHANGELOG.md
@tiagonbotelho I think I didn't quite get what you said, can you elaborate ?

2016-09-24 11:41 UTC, tiagonbotelho commented on CHANGELOG.md
I will merge this and make it myself :) no worries

2016-09-24 11:41 UTC, merged